# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache:
  - packages

r_packages:
  - goodpractice
  - vcr

matrix:
  include:
  - r: oldrel
  - r: release
    after_success:
    -  R -e "covr::codecov(line_exclusions = list('R/finbif_request_token.R' = 33:69))"
    -  R -e "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert = TRUE, value = TRUE))"
  - r: devel
  - r: release
    os: osx
