language: r
os: linux
dist: xenial
cache:
- packages
addons:
  apt:
    packages:
    - libudunits2-dev
    - libgdal-dev
    - libgeos-dev
    - libproj-dev
  homebrew:
    packages:
    - udunits
    - cairo
r_packages:
  - goodpractice
jobs:
  include:
  - r: oldrel
  - r: release
    after_success:
    - R -e "covr::codecov(line_exclusions = list('R/finbif_request_token.R' = 35:72),
      branch = Sys.getenv('TRAVIS_BRANCH'))"
    - R -e "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(),
      invert = TRUE, value = TRUE))"
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      cleanup: false
  - r: devel
  - r: release
    os: osx
notifications:
  slack:
    rooms:
      secure: ozcpfdk3i6CAHbig2eu9rElNI2P4xUs16cbM0NfKkEOz+dWlWJDWtWr9duM6XLioZusbSdcLK50ANuTb8cq4vGL9RnRsfRJsx7HlLb0OtOLEKYoVw8ZI+BSFK18j4QKPpqRnxerNK9J593+FxlGzBw/oeZaFIM89VunpwcF+pQ3Y9xxwB9RFrpHa0a9VYTfWbBXw5XkXwjmivTb93fkfaj5f0vEiWyNF/Alh9EwD2ovX1pZp/P8Po4C6+lq0gON7QH70JcstYvMvDTjYI/fTfdC7F7nFYyVa1h9wAyqy4O9ZfQXTfQtHW7xMrzL3UnciBRzplGNK4kk+eag9iIFfHHQMc/8BYTu03/yu4GxOW0Da8avGNMKYs1ecducV5CAAl9qdFALsG5YaY+chpU5K3zO2+ekCTtacvOX9r0TWlAmri3nUpB4oQrIWiiD0qODJyy5sQP8Ro0YGe+7+Wu8K0YxbjgaYvku3EoCh6+rZ+S2VchVptptSoy46aRoErJW4pdCyfi+voD5Uk+fDsQA4MPPeAteJ2NJGlGZQp+d44LjAas+/id5k1LAu5im2FNlYwFfrn6lt0XjXPbUsoCrRbMpXLhSftOELGJxDuWo5BJGuYDHz+7km+E9k1BS4WzdvHmt7kM8aUamP9fio/vcewcSh6PaZd0lbnNVzuKLzUdI=
    on_success: always
    on_failure: always
