source("data-raw/variables.R")
source("data-raw/filters.R")
source("data-raw/status.R")
source("data-raw/informal_groups.R")
source("data-raw/habitat_types.R")
source("data-raw/taxon_ranks.R")
source("data-raw/countries.R")
source("data-raw/provinces.R")
source("data-raw/municipalities.R")
source("data-raw/bird_association_area.R")
source("data-raw/finnish_occurrence.R")
source("data-raw/sources.R")
source("data-raw/record_basis.R")
source("data-raw/life_stage.R")
source("data-raw/sex.R")
source("data-raw/restriction.R")
source("data-raw/misc.R")
usethis::use_data(
  var_names,
  filter_names,
  administrative_status,
  red_list_status,
  informal_group,
  informal_group_reported,
  primary_habitat,
  primary_secondary_habitat,
  taxon_rank,
  country,
  province,
  municipality,
  bird_assoc_area,
  finnish_occurrence_status,
  finnish_occurrence_status_neg,
  source,
  record_basis,
  superrecord_basis,
  life_stage,
  sex,
  restriction_reason,
  restriction_level,
  quality_issues,
  taxon_reliability,
  internal = TRUE,
  overwrite = TRUE
)
