source("data-raw/variables.R")
source("data-raw/variables_test.R")
source("data-raw/citable_file_variables.R")
source("data-raw/citable_file_variables_test.R")
source("data-raw/lite_download_file_variables.R")
source("data-raw/lite_download_file_variables_test.R")
source("data-raw/filters.R")
source("data-raw/filters_test.R")
source("data-raw/status.R")
source("data-raw/informal_groups.R")
source("data-raw/habitat_types.R")
source("data-raw/taxon_ranks.R")
source("data-raw/countries.R")
source("data-raw/regions.R")
source("data-raw/bio_provinces.R")
source("data-raw/municipalities.R")
source("data-raw/bird_association_area.R")
source("data-raw/finnish_occurrence.R")
source("data-raw/sources.R")
source("data-raw/record_basis.R")
source("data-raw/life_stage.R")
source("data-raw/sex.R")
source("data-raw/restriction.R")
source("data-raw/misc.R")
source("data-raw/location_tag.R")
source("data-raw/complete_list_type.R")
source("data-raw/atlas.R")
usethis::use_data(
  var_names,
  var_names_test,
  has_value,
  has_value_test,
  cite_file_vars,
  cite_file_vars_test,
  lite_download_file_vars,
  lite_download_file_vars_test,
  filter_names,
  filter_names_test,
  regulatory_status,
  red_list_status,
  threatened_status,
  informal_groups,
  informal_groups_reported,
  primary_habitat,
  primary_secondary_habitat,
  taxon_rank,
  orig_taxon_rank,
  country,
  region,
  bio_province,
  municipality,
  bird_assoc_area,
  finnish_occurrence_status,
  finnish_occurrence_status_neg,
  source,
  record_basis,
  superrecord_basis,
  life_stage,
  sex,
  restriction_reason,
  restriction_level,
  quality_issues,
  collection_quality,
  record_quality,
  record_reliability,
  complete_list_type,
  supported_langs,
  location_tag,
  atlas_code,
  atlas_class,
  internal = TRUE,
  overwrite = TRUE
)

# exported data
source("data-raw/finland_map.R")
