#' FinBIF record variables
#'
#' FinBIF record variables that can selected.
#'
#' @section Misc:
#' Other variables:
#'
#' - `scientific_name` Character.
#'   Scientific name of taxon.
#' - `taxon_rank`
#' - `abundance`
#' - `abundance_string`
#' - `country`
#' - `province`
#' - `municipality`
#' - `lat_wgs84`
#' - `lon_wgs84`
#' - `wkt_wgs84`
#' - `line_length_m`
#' - `area_m2`
#' - `date_start`
#' - `date_end`
#' - `hour_start`
#' - `hour_end`
#' - `minute_start`
#' - `minute_end`
#' - `record_id`
#' - `individual_id`
#' - `event_id`
#' - `collection_id`
#' - `annotation_count`
#' - `annotation_person`
#' - `annotation_person_name`
#' - `annotation_system`
#' - `annotation_system_name`
#' - `annotation_class`
#' - `annotation_created`
#' - `annotation_id`
#' - `annotation_invasive_control_effectiveness`
#' - `annotation_notes`
#' - `annotation_opinion`
#' - `annotation_type`
#' - `author`
#' - `is_breeding_site`
#' - `determiner`
#' - `record_fact_decimal`
#' - `record_fact`
#' - `record_fact_integer`
#' - `record_fact_value`
#' - `female_abundance`
#' - `male_abundance`
#' - `annotated_taxon_id`
#' - `pair_abundance`
#' - `is_unidentifiable`
#' - `invasive_control_effectiveness`
#' - `invasive_control`
#' - `life_stage`
#' - `orig_taxon_checklist`
#' - `orig_taxon_cursive`
#' - `orig_taxon_finnish`
#' - `orig_taxon_id`
#' - `orig_informal_groups`
#' - `orig_qname`
#' - `orig_taxon_scientific_name`
#' - `orig_scientific_name_author`
#' - `orig_scientific_display_name`
#' - `orig_taxon_rank`
#' - `orig_name_vernacular`
#' - `taxon_checklist`
#' - `taxon_name_cursive`
#' - `taxon_finnish`
#' - `taxon_id`
#' - `informal_groups`
#' - `qname`
#' - `scientific_name_author`
#' - `scientific_display_name`
#' - `vernacular_name`
#' - `record_media_author`
#' - `record_media_caption`
#' - `record_media_copyright`
#' - `record_media_url`
#' - `record_media_license_abbr`
#' - `record_media_license_id`
#' - `record_media_type`
#' - `record_thumbnail_square`
#' - `record_thumbnail`
#' - `record_media_count`
#' - `record_notes`
#' - `any_issues`
#' - `record_issue`
#' - `record_issue_message`
#' - `record_issue_source`
#' - `record_reliable`
#' - `taxon_issue_message`
#' - `taxon_reliability`
#' - `taxon_issue_source`
#' - `record_basis`
#' - `reference_publication`
#' - `reported_informal_group`
#' - `reported_taxon_confidence`
#' - `reported_taxon_id`
#' - `sex`
#' - `superrecord_basis`
#' - `taxon_verbatim`
#' - `type_specimen`
#' - `record_order`
#' - `wild_status`
#' - `conservation_reason_secured`
#' - `date_created`
#' - `custom_reason_secured`
#' - `data_quarantine_period_reason_secured`
#' - `document_id`
#' - `editor_user_ids`
#' - `document_fact_decimal`
#' - `document_fact_content`
#' - `document_fact_integer`
#' - `document_fact_value`
#' - `first_load_date`
#' - `form_id`
#' - `keywords`
#' - `license`
#' - `editor_name`
#' - `editor_id`
#' - `editor_user_id`
#' - `load_date`
#' - `document_media_author`
#' - `document_media_caption`
#' - `document_media_copyright`
#' - `document_media_url`
#' - `document_media_license_abbr`
#' - `document_media_license_id`
#' - `document_media_type`
#' - `document_thumbnail_square`
#' - `document_thumbnail`
#' - `document_media_count`
#' - `modified_date`
#' - `bird_assoc_area`
#' - `bird_assoc_area_id`
#' - `location_collection_id`
#' - `location_id`
#' - `location_municipality`
#' - `location_municipality_id`
#' - `location_name`
#' - `location_lat_kkj`
#' - `location_lon_kkj`
#' - `locationid`
#' - `document_notes`
#' - `partial`
#' - `document_issue`
#' - `document_issue_message`
#' - `document_issue_source`
#' - `document_reliablity`
#' - `secured_level`
#' - `secured_reasons`
#' - `secured`
#' - `source_id`
#' - `province_verbatim`
#' - `century`
#' - `day`
#' - `ordinal_day_start`
#' - `ordinal_day_end`
#' - `decade`
#' - `lat_max_euref`
#' - `lat_min_euref`
#' - `lon_max_euref`
#' - `lon_min_euref`
#' - `wkt_euref`
#' - `month`
#' - `season_start`
#' - `season_end`
#' - `lat_max_wgs84`
#' - `lat_min_wgs84`
#' - `lon_max_wgs84`
#' - `lon_min_wgs84`
#' - `lat_005_wgs84`
#' - `lon_005_wgs84`
#' - `lat_01_wgs84`
#' - `lon_01_wgs84`
#' - `lat_05_wgs84`
#' - `lon_05_wgs84`
#' - `lat_1_wgs84`
#' - `lon_1_wgs84`
#' - `year`
#' - `lat_max_kkj`
#' - `lat_min_kkj`
#' - `lon_max_kkj`
#' - `lon_min_kkj`
#' - `lat_100_kkj`
#' - `lon_100_kkj`
#' - `lat_100_center_kkj`
#' - `lon_100_center_kkj`
#' - `lat_10_kkj`
#' - `lon_10_kkj`
#' - `lat_10_center_kkj`
#' - `lon_10_center_kkj`
#' - `lat_1_kkj`
#' - `lon_1_kkj`
#' - `lat_1_center_kkj`
#' - `lon_1_center_kkj`
#' - `lat_50_kkj`
#' - `lon_50_kkj`
#' - `lat_50_center_kkj`
#' - `lon_50_center_kkj`
#' - `wkt_kkj`
#' - `coordinates_verbatim`
#' - `country_verbatim`
#' - `date_time`
#' - `event_fact_decimal`
#' - `event_fact`
#' - `event_fact_integer`
#' - `event_fact_value`
#' - `event_order`
#' - `higher_geography`
#' - `province_id`
#' - `province_ids`
#' - `coordinate_accuracy`
#' - `country_id`
#' - `municipalities_ids`
#' - `municipality_id`
#' - `province_source`
#' - `coordinates_source`
#' - `country_source`
#' - `municipality_source`
#' - `observers_name`
#' - `observers_id`
#' - `observers_user_id`
#' - `locality`
#' - `event_media_author`
#' - `event_media_caption`
#' - `event_media_copyright`
#' - `event_media_url`
#' - `event_media_license_abbr`
#' - `event_media_license_id`
#' - `event_media_type`
#' - `event_thumbnail_square`
#' - `event_thumbnail`
#' - `event_media_count`
#' - `municipality_verbatum`
#' - `province_verbatum2`
#' - `event_notes`
#' - `observer_user_ids`
#' - `event_issue`
#' - `event_issue_message`
#' - `event_issue_source`
#' - `location_issue`
#' - `location_issue_message`
#' - `location_issue_source`
#' - `time_issue`
#' - `time_issue_message`
#' - `time_issue_source`
#' - `taxon_cenus_id`
#' - `taxon_census_type`
#' - `team`
#'
#' @name variables
NULL
